version: '3'

services:

  #nginx:
  #  image: nginx:1.11
  #  depends_on:
  #    - php
  #  ports:
  #    - 80:80
  #  networks:
  #    - front-tier
  #  volumes:
  #    - ./public:/var/www/html/public:ro
  #    - ./docker/nginx/habitatsaintquentinois.conf:/etc/nginx/conf.d/default.conf:ro

  #php:
  #  build: ./docker/php
  #  working_dir: /var/www/html
  #  environment:
  #    - XDEBUG_CONFIG="remote_host=10.254.254.254"
  #    - PHP_IDE_CONFIG="serverName=local.habitatsaintquentinois.fr"
  #  depends_on:
  #    - mysql
  #  expose:
  #    - 9000
  #  networks:
  #    - front-tier
  #    - back-tier
  #  volumes:
  #    - ./:/var/www/html:cached

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: habitatsaintquentinois
      MYSQL_USER: hsq
      MYSQL_PASSWORD: hsq
      MYSQL_ROOT_PASSWORD: hsq
    ports:
      - 3306:3306

#networks:
#  front-tier:
#    driver: bridge
#  back-tier:
#    driver: bridge